services:
    app:
        image: louislam/its-mytabs:1
        ports:
            # Host Port:Container Port
            - "47777:47777"
        volumes:
            # Host Path:Container Path
            - ./data:/app/data

            # OPTIONAL: Uncomment to mount a media library of existing audio files.
            # Note that this should be mounted read-only. 
            # /path/to/audo/library:/app/library:ro

        environment:
            # OPTIONAL: Uncomment to specify the location of a media library. Note
            # that its-mytabs will not automatically search for the library, just
            # because it's mounted at the above location.
            # LIBRARY_DIR=/app/library

        restart: unless-stopped
